### ISSUE TITLE
java.lang.NoSuchMethodError: android.view.View.setX

### ISSUE THREAD

**Issue by sonlv-enguys** [Grishu/TinderView-Control#3]
Hi Grishu,

I run my app throw error: java.lang.NoSuchMethodError: android.view.View.setX at com.example.tinderview_demo.MainActivity.onCreate(MainActivity.java:57)

AndroidManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.tinderview_demo"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="10"
        android:targetSdkVersion="19" />

    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name="com.example.tinderview_demo.MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.tinderview_demo.DetailsActivity" >
        </activity>
    </application>

</manifest>
```

**Comment by sonlv-enguys** [comment]
I using galaxy y. Android 2.3.6

**Comment by Grishu** [comment]
Please post your full logcat error. And also try to clean your project once.

**Comment by sonlv-enguys** [comment]
Hi @Grishu 

my full log

```
09-07 12:54:03.203: E/AndroidRuntime(12910): FATAL EXCEPTION: main
09-07 12:54:03.203: E/AndroidRuntime(12910): java.lang.NoSuchMethodError: android.view.View.setRotation
09-07 12:54:03.203: E/AndroidRuntime(12910):    at com.example.tinderview_demo.MainActivity.onCreate(MainActivity.java:62)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.app.ActivityThread.access$1500(ActivityThread.java:117)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.os.Looper.loop(Looper.java:130)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at android.app.ActivityThread.main(ActivityThread.java:3687)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at java.lang.reflect.Method.invokeNative(Native Method)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at java.lang.reflect.Method.invoke(Method.java:507)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
09-07 12:54:03.203: E/AndroidRuntime(12910):    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by sonlv-enguys** [comment]
@Grishu  help me. @@@@@@

**Comment by MichaelEvans** [comment]
I think you need something like Nine Old Androids if you're supporting API < 11

**Comment by sonlv-enguys** [comment]
Hi @MichaelEvans  . Can you tell me more!

**Comment by Grishu** [comment]
Check out i have updated my code and its not throwing any errors now.

**Comment by sonlv-enguys** [comment]
Hi @Grishu  I using galaxy y. Android 2.3.6
